### ISSUE TITLE
prepare the ground truth depth maps

### ISSUE THREAD

**Issue by wwj-53** [ShuweiShao/AF-SfMLearner#57]
Based on your description，the directory of dataset structure is shown as ：
/path/to/endovis_data/
  dataset1/
    keyframe1/
      image_02/
        data/
          0000000001.png

but  after processing according to your method, it looks like this:
/path/to/endovis_data/
  dataset1/
    keyframe1/
        data/
          0000000001.png
There is no image folder name available.

When I run CUDA_VISIBLE_DEVICES=0 python export_gt_depth.py --data_path /media/wwj/aj_new/dataset_2 --split endovis，
The error is as follows：
(endodac) wwj@cpnt:~/3DGS/AF-SfMLearner$ CUDA_VISIBLE_DEVICES=0 python export_gt_depth.py --data_path /media/wwj/aj_new/dataset_2 --split endovis
Exporting ground truth depths for endovis
1
dataset3/keyframe4
[ WARN:0@0.005] global loadsave.cpp:241 findDecoder imread_('/media/wwj/aj_new/dataset_2/dataset3/keyframe4/data/groundtruth/scene_points000389.tiff'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/home/wwj/3DGS/AF-SfMLearner/export_gt_depth.py", line 61, in <module>
    export_gt_depths_SCARED()
  File "/home/wwj/3DGS/AF-SfMLearner/export_gt_depth.py", line 48, in export_gt_depths_SCARED
    depth_gt = depth_gt[:, :, 0]
TypeError: 'NoneType' object is not subscriptable

I have changed line 44 from "image-02/data/roundtruth" to "data/roundtruth" (otherwise it will not run according to the structure of my dataset)

**Comment by suxuanya** [comment]
I also encountered this problem. Have you solved it?

**Comment by wwj-53** [comment]
> I also encountered this problem. Have you solved it?

no

**Comment by ShuweiShao** [comment]
Hi all,

Please create the image_02 folder by yourself and put the data in it. The format follows the KITTI dataset and ''image_02'' indicates the left frames.

**Comment by suxuanya** [comment]
Thanks a lot.

**Comment by mahirjain01** [comment]
Please elaborate the solution, I am still getting the same error after manually creating the folder image_02.
